// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZsQRBVBdUy9rH76QtpbTynLUziNBri8',
    appId: '1:843207832374:web:8ab9cb5c297be36afdb997',
    messagingSenderId: '843207832374',
    projectId: 'historic-street',
    authDomain: 'historic-street.firebaseapp.com',
    databaseURL: 'https://historic-street-default-rtdb.firebaseio.com',
    storageBucket: 'historic-street.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAixz1AxwMu1B8U00m13VbjWexNqwlc4',
    appId: '1:843207832374:android:abad60148734af20fdb997',
    messagingSenderId: '843207832374',
    projectId: 'historic-street',
    databaseURL: 'https://historic-street-default-rtdb.firebaseio.com',
    storageBucket: 'historic-street.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA81lwyAA_GYFnWdfUuMTj5XIqgKsNIV7o',
    appId: '1:843207832374:ios:d24f5720ba70835efdb997',
    messagingSenderId: '843207832374',
    projectId: 'historic-street',
    databaseURL: 'https://historic-street-default-rtdb.firebaseio.com',
    storageBucket: 'historic-street.appspot.com',
    iosClientId: '843207832374-0h18g9emgjq9lhmokbfhei7ldfm3mjnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.historicStreet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA81lwyAA_GYFnWdfUuMTj5XIqgKsNIV7o',
    appId: '1:843207832374:ios:b18be54a596a5210fdb997',
    messagingSenderId: '843207832374',
    projectId: 'historic-street',
    databaseURL: 'https://historic-street-default-rtdb.firebaseio.com',
    storageBucket: 'historic-street.appspot.com',
    iosClientId: '843207832374-lmtstkd6pmil2p7ao4mqfro45i70qr82.apps.googleusercontent.com',
    iosBundleId: 'com.example.historicStreet.RunnerTests',
  );
}
